version: "3.8"
services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
      
  mongo-express:
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=localhost
        - ME_CONFIG_MONGODB_PORT=$MONGODB_LOCAL_PORT
        - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
        - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
        - ME_CONFIG_BASICAUTH_USERNAME=$MONGOEXPRESS_LOGIN
        - ME_CONFIG_BASICAUTH_PASSWORD=$MONGOEXPRESS_PASSWORD
    depends_on:
        - mongo
    ports:
      - "$MONGOEXPRESS_LOCAL_PORT:$MONGOEXPRESS_DOCKER_PORT"

volumes:
  db:

